version: "3.8"

services:
  nest-tdd:
    image: nest-tdd
    #environment:
      #MONGO_URL: "mongodb://db:27017/test"
    #depends_on:
      #- db
    ports:
      - "3000-3005:3000"

  #db:
    #image: mongo
